providers:
  - name: example-aa
    base_url: https://api.example-aa.com/v1
    auth_token_env: EXAMPLE_AA_TOKEN
    capabilities:
      - planning
      - execution
agents:
  - id: planner_bot
    provider: example-aa
    skills:
      - planning
      - coordination
    metadata:
      tier: beta
  - id: executor_bot
    provider: example-aa
    skills:
      - execution
      - validation
    metadata:
      tier: beta
tasks:
  - id: discovery_brief
    description: Thu thập yêu cầu khách hàng và sinh contract placeholder.
    required_skills:
      - planning
      - coordination
    sla_minutes: 10
  - id: sanitize_audit
    description: Chạy checklist sanitize trước khi public.
    required_skills:
      - execution
      - validation
    sla_minutes: 5
ssot_bucket: local
